import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../utils/api';
import { getCart, saveCart, type CartItem } from '../utils/cart';
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n);
type Pay={orderId:number;orderCode:string;qrCodeUrl?:string;deeplink?:string;payUrl?:string;expiredAt:string};
export default function Checkout(){const nav=useNavigate(),[items]=useState<CartItem[]>(getCart),[pay,setPay]=useState<Pay|null>(null),[seconds,setSeconds]=useState(0),[error,setError]=useState('');const [f,setF]=useState({recipient:'',phone:'',address:'',note:''});const subtotal=useMemo(()=>items.reduce((s,x)=>s+x.price*x.quantity,0),[items]),shipping=0;
useEffect(()=>{if(!pay)return;const update=()=>setSeconds(Math.max(0,Math.ceil((new Date(pay.expiredAt).getTime()-Date.now())/1000)));update();const t=setInterval(update,1000),p=setInterval(async()=>{try{const r=await api.get(`/orders/${pay.orderId}`);if(r.data.paymentStatus==='PAID'){saveCart([]);nav('/orders?paid=1')}}catch{}},5000);return()=>{clearInterval(t);clearInterval(p)}},[pay,nav]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const r=await api.post('/orders',{items,recipientName:f.recipient,phone:f.phone,address:f.address,note:f.note,shippingFee:shipping,paymentMethod:'SEPAY'});saveCart([]);setPay(r.data)}catch(e:any){setError(e.response?.data?.message??'Không thể tạo đơn hàng.')}};
if(!items.length&&!pay)return <div className="max-w-2xl mx-auto px-4 py-20 text-center"><h1 className="text-2xl font-bold">Giỏ hàng đang trống</h1><Link className="mt-5 inline-block text-emerald-600" to="/products">Quay lại danh mục</Link></div>;
if(pay){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');return <div className="max-w-xl mx-auto px-4 py-12"><div className="rounded-2xl border bg-white p-7 text-center"><h1 className="text-2xl font-bold text-[#0b6e4f]">Thanh toán qua SePay</h1><p className="mt-3 font-bold">⏱ Còn lại: {m}:{s}</p><div className="mt-4 h-2 rounded-full bg-gray-100"><div className="h-full bg-emerald-600" style={{width:`${Math.min(100,seconds/18)}%`}}/></div>{pay.qrCodeUrl?<img src={pay.qrCodeUrl} alt="Mã QR thanh toán SePay" className="mx-auto mt-7 h-60 w-60"/>:<p className="mt-8">Đang tạo mã QR…</p>}<p className="mt-5">Mã đơn: <strong>{pay.orderCode}</strong></p><p className="mt-2">Số tiền: <strong>{money(subtotal+shipping)}</strong></p><p className="mt-5 text-sm text-gray-500">Quét QR bằng ứng dụng ngân hàng. Hệ thống sẽ tự xác nhận khi nhận đúng số tiền và mã đơn.</p><button type="button" onClick={()=>api.patch(`/orders/${pay.orderId}/cancel`).finally(()=>nav('/orders'))} className="mt-5 text-sm text-rose-600">Huỷ đơn hàng</button></div></div>}
return <form onSubmit={submit} className="max-w-6xl mx-auto px-4 py-10"><h1 className="text-3xl font-bold">Thanh toán</h1>{error&&<p className="mt-4 rounded-lg bg-rose-50 p-3 text-rose-700">{error}</p>}<div className="mt-7 grid lg:grid-cols-[1fr_380px] gap-7"><section className="space-y-6"><div className="rounded-2xl border bg-white p-6"><h2 className="font-bold">Thông tin nhận hàng</h2><div className="mt-4 grid sm:grid-cols-2 gap-4"><input required placeholder="Họ tên" className="border rounded-lg p-3" value={f.recipient} onChange={e=>setF({...f,recipient:e.target.value})}/><input required placeholder="Số điện thoại" className="border rounded-lg p-3" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></div><input required placeholder="Địa chỉ giao hàng" className="mt-4 w-full border rounded-lg p-3" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><textarea placeholder="Ghi chú" className="mt-4 w-full border rounded-lg p-3" value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></div><div className="rounded-2xl border border-emerald-200 bg-white p-6"><h2 className="font-bold">Phương thức thanh toán</h2><div className="mt-4 flex gap-3 rounded-lg border border-emerald-600 bg-emerald-50 p-4"><span className="text-xl">▣</span><span><strong>SePay QR</strong><small className="block text-gray-500">Quét mã QR bằng ứng dụng ngân hàng để hoàn tất thanh toán.</small></span></div></div></section><aside className="h-fit rounded-2xl border bg-white p-6"><h2 className="font-bold">Đơn hàng của bạn</h2>{items.map((x,i)=><div key={i} className="flex justify-between border-b py-4 text-sm"><span>{x.name}<small className="block text-gray-500">{x.sizeLabel} × {x.quantity}</small></span><strong>{money(x.price*x.quantity)}</strong></div>)}<p className="mt-4 flex justify-between"><span>Tổng</span><strong className="text-emerald-600">{money(subtotal+shipping)}</strong></p><button className="mt-6 w-full rounded-lg bg-emerald-600 py-3 font-semibold text-white hover:bg-emerald-700">Tạo mã QR SePay</button></aside></div></form>}
