using FurniMatch.Api.Data;
using FurniMatch.Api.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.Text;

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// Dynamically bind port for Render / container environments
var port = Environment.GetEnvironmentVariable("PORT");
if (!string.IsNullOrEmpty(port))
{
    builder.WebHost.UseUrls($"http://0.0.0.0:{port}");
}

// Add services to the container.
builder.Services.AddControllers().AddJsonOptions(options => 
{
    options.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
});

// Add DbContext (PostgreSQL / Supabase)
builder.Services.AddDbContext<FurniMatchDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

// Add Email Service
builder.Services.AddScoped<IEmailService, EmailService>();

// Add Photo Service (Cloudinary)
builder.Services.AddScoped<IPhotoService, PhotoService>();

builder.Services.AddHttpClient<MomoPaymentService>();
builder.Services.Configure<SePayOptions>(builder.Configuration.GetSection("SePay"));
builder.Services.AddHttpClient<SePayPaymentService>(client => client.BaseAddress = new Uri("https://userapi.sepay.vn/v2/"));

// Escrow & Payout Services
builder.Services.AddScoped<EscrowService>();
builder.Services.AddHostedService<PayoutBackgroundService>();

// Add Authentication
var jwtSettings = builder.Configuration.GetSection("Jwt");
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtSettings["Issuer"],
        ValidAudience = jwtSettings["Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSettings["Key"]!))
    };
});

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Add CORS - allow any origin for easy deployment on Render / Vercel
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.SetIsOriginAllowed(_ => true)
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "FurniMatch API v1");
    c.RoutePrefix = "swagger";
});

using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<FurniMatchDbContext>();

    try
    {
        // Auto-create database schema on PostgreSQL / Supabase if not exists
        context.Database.EnsureCreated();

        // Ensure ImageUrl and ImagesJson columns exist in QuotationRequests
        try
        {
            context.Database.ExecuteSqlRaw(@"ALTER TABLE ""QuotationRequests"" ADD COLUMN IF NOT EXISTS ""ImageUrl"" text;");
            context.Database.ExecuteSqlRaw(@"ALTER TABLE ""QuotationRequests"" ADD COLUMN IF NOT EXISTS ""ImagesJson"" text;");
        }
        catch { }

        // Ensure ChatMessages table exists
        try
        {
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""ChatMessages"" (
                    ""ChatMessageId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""SenderId"" integer NOT NULL,
                    ""ReceiverId"" integer NOT NULL,
                    ""ProductId"" integer NULL,
                    ""ProductPrice"" numeric(18,2) NULL,
                    ""Content"" text NOT NULL,
                    ""IsRead"" boolean NOT NULL DEFAULT FALSE,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
                    CONSTRAINT ""FK_ChatMessages_Users_SenderId"" FOREIGN KEY (""SenderId"") REFERENCES ""Users"" (""UserId"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_ChatMessages_Users_ReceiverId"" FOREIGN KEY (""ReceiverId"") REFERENCES ""Users"" (""UserId"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_ChatMessages_Products_ProductId"" FOREIGN KEY (""ProductId"") REFERENCES ""Products"" (""ProductId"") ON DELETE SET NULL
                );
                ALTER TABLE ""ChatMessages"" ADD COLUMN IF NOT EXISTS ""ProductPrice"" numeric(18,2) NULL;
                CREATE INDEX IF NOT EXISTS ""IX_ChatMessages_SenderId"" ON ""ChatMessages"" (""SenderId"");
                CREATE INDEX IF NOT EXISTS ""IX_ChatMessages_ReceiverId"" ON ""ChatMessages"" (""ReceiverId"");
                CREATE INDEX IF NOT EXISTS ""IX_ChatMessages_CreatedAt"" ON ""ChatMessages"" (""CreatedAt"");
            ");
        }
        catch { }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[Database Init Warning]: {ex.Message}");
    }

    // Đồng bộ các đơn hàng đã được duyệt khiếu nại (PayoutStatus == REFUNDED) để PaymentStatus cũng là REFUNDED
    try
    {
        var pastRefundedOrders = context.Orders
            .Where(o => o.PayoutStatus == "REFUNDED" && o.PaymentStatus != "REFUNDED")
            .ToList();
        if (pastRefundedOrders.Any())
        {
            foreach (var ord in pastRefundedOrders)
            {
                ord.PaymentStatus = "REFUNDED";
                ord.UpdatedAt = DateTime.UtcNow;
            }
            context.SaveChanges();
        }
    }
    catch (Exception syncEx)
    {
        Console.WriteLine($"[Refund Sync Warning]: {syncEx.Message}");
    }

    if (!context.Categories.Any())
    {
        context.Categories.AddRange(
            new FurniMatch.Api.Models.Category { Name = "Tủ Bếp" },
            new FurniMatch.Api.Models.Category { Name = "Bàn Trà" },
            new FurniMatch.Api.Models.Category { Name = "Sofa" },
            new FurniMatch.Api.Models.Category { Name = "Giường Ngủ" }
        );
        context.SaveChanges();
    }

    // Seed default CommissionConfig (5%) if none exists
    if (!context.CommissionConfigs.Any())
    {
        context.CommissionConfigs.Add(new FurniMatch.Api.Models.CommissionConfig
        {
            CommissionRate = 5.0m,
            IsActive = true,
            Note = "Tỷ lệ hoa hồng mặc định",
            EffectiveFrom = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        });
        context.SaveChanges();
    }

    // Seed Admin Role & User
    var adminRole = context.Roles.FirstOrDefault(r => r.RoleName == "ADMIN");
    if (adminRole == null)
    {
        adminRole = new FurniMatch.Api.Models.Role { RoleName = "ADMIN" };
        context.Roles.Add(adminRole);
        context.SaveChanges();
    }

    if (!context.Users.Any(u => u.Email == "admin@furnimatch.com"))
    {
        var adminUser = new FurniMatch.Api.Models.User
        {
            FullName = "System Administrator",
            Email = "admin@furnimatch.com",
            Phone = "0123456789",
            PasswordHash = BCrypt.Net.BCrypt.HashPassword("Admin@123"),
            RoleId = adminRole.RoleId,
            Status = "ACTIVE"
        };
        context.Users.Add(adminUser);
        context.SaveChanges();
    }

    // Seed Customer Role
    var customerRole = context.Roles.FirstOrDefault(r => r.RoleName == "CUSTOMER");
    if (customerRole == null)
    {
        customerRole = new FurniMatch.Api.Models.Role { RoleName = "CUSTOMER" };
        context.Roles.Add(customerRole);
        context.SaveChanges();
    }

    // Seed Seller Role
    var sellerRole = context.Roles.FirstOrDefault(r => r.RoleName == "SELLER");
    if (sellerRole == null)
    {
        sellerRole = new FurniMatch.Api.Models.Role { RoleName = "SELLER" };
        context.Roles.Add(sellerRole);
        context.SaveChanges();
    }

    // Seed Category Tranh Treo Tường
    var artCategory = context.Categories.FirstOrDefault(c => c.Name.Contains("Tranh"));
    if (artCategory == null)
    {
        artCategory = new FurniMatch.Api.Models.Category
        {
            Name = "Tranh Treo Tường",
            Description = "Tranh tráng gương ceramic pha lê, tranh canvas nghệ thuật và tranh phong thủy trang trí nội thất."
        };
        context.Categories.Add(artCategory);
        context.SaveChanges();
    }
    else
    {
        artCategory.Name = "Tranh Treo Tường";
        artCategory.Description = "Tranh tráng gương ceramic pha lê, tranh canvas nghệ thuật và tranh phong thủy trang trí nội thất.";
        context.SaveChanges();
    }


}

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor | Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto
});

if (!app.Environment.IsProduction())
{
    app.UseHttpsRedirection();
}

app.UseStaticFiles();

app.UseCors("AllowAll");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
